version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - $(aws ecr get-login --no-include-email --region ap-northeast-1)
  build:
    commands:
      - docker build -t hgk/app .
  post_build:
    commands:
      - docker tag hgk/app:latest 756081124733.dkr.ecr.ap-northeast-1.amazonaws.com/hgk/app:latest
      - docker push 756081124733.dkr.ecr.ap-northeast-1.amazonaws.com/hgk/app:latest
