version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
    #finally:
      # - command
      # - command
  pre_build:
    commands:
      - echo "docker login ..."
      - docker login -u AWS -p eyJwYXlsb2FkIjoiblc1anhHYnZvWW9qT2V3Q1p5TnorQkdVSVNKQzhJWXkzRGJHbW85MmkxSmZpdFl1VithVG5vQnZkTmtiTTlQenRWMVB2L2kwdStZenVjL25qSkZKU1prdTc5azZMd2ttVURFWk5oc0ozNGxBTFRuTzV6YlQ2d3JRclZBRWpLdlE0L29IakdUK0FjQlVYcVhjd053bTIyNDdlNmpQU1FMdy9Ja1FBaVZXdXhtaHBrRjRKSHMxdGlHOTdVRHhwZk9EQnRZOUU5TkRmSlJsekNTZDMyenl6bTlseXM3bjh5djZnTFV4b3p0a21WTldDWWg2d1RITkVXVmhNSkZZaTJ1a0pPMkRKMXNiKzZxVFFveDZ2SXZuU1liaUlHZlFhbFdXZXhWMnVJL2x6aFFPR1NtWjZ0eFVkQlR1SUFpeGd1K0V5TEFjQ0QzUkd5YVUyMUplUFU2ODB2eHhiN04zcmVEUW1xSTNMSU9BNEVBZDJVZ0JmMDRCeXNCeFhXREpIV0RYeDQ5ZU1ZY3FXTVJlUEg2eUhkeFhidGJKbUNwcFJOb05HNUxpbEY3N2VCeUFIM0duSkJkYUhzVml5R2M1d2xuZFJpcm92MzdzNTltYS9HbVZUL0E0Rjk5dVBCQ0lnNExLVFRiM2ljQnVrUEhyVm8rUEkvM01Ra01mWGpPU2hqMDR5N2swTTliek1UTmdyalhCQkNUU0NiVlFsQkw0SlcwWGlHRjMzaTZVTit1TVo2U0RnZnNxaGYvNXZ1RzVNT2lCUmJsM2psS2t3U210bVN3ZWxRbHdsSDJPRlZvcmwwREl2WHlOaWQyUWpLSmNCTU5FR2lKOTlZcnl2MjhMUjBIUk1mVHdrMlJHU2MxY1g2Q2xZWHdMZzlqeFBSUGVPMEFpK2MrY2lKMlQ3TUFnRUR2cXluQlZQVEFhN3dHYy9OMHdpWmJKNFdCQkh6WmJRYlVXVHB6MWYrYWxHWGtJb05mMTNnREdwajZUVE1vSEx1cWw3bkJTT2dUQyt6U1AxZmR1T1loUFhrMVFZSzcrTXY5RncwWDlQcDVjUGNUMkdQVDFUeVRyOVhhMG9wSXhQUUtHZysyUThuVzdKL2Y3SGlDQTgwN3k4aGV3K3A2WG9PU3gyVDJ1ekdPem9mUWE2Tm9VZUJWSW42Qndlb0VIdGcvSm9CVDd0SDNSR1NVUzJjbTNGaWVTYkNZaXJ1eFkwa2ducDg4YjFheU1aSlNVeUVKYnFyOSt2RVUvZDRITVBDNUVGbUMwVVl3WkZaTkdHM1VkYWZucnF3QSsxTzhzaUFKN0JvZWdFTDhQRW9GQm44Q3RlQ0lFK0ZzMlA5QTZHRHZ5S3dwQVFIVnRUUXFXQ29kU2N6TlVvcUpudU1NM2FjZ01LampmZjZjSWtycG1NVUhZRnZvbTF6RjJ0Q1Fqa0Q1bHA1bFVGdnE5Nk1tT3gzcFZHMnJsbU5BY3pseGdUcFkveVBCcmRqWUdLeFBlZGZNamF6bUVORlplR2c9PSIsImRhdGFrZXkiOiJBUUVCQUhnQU1mS0RsSW9wQzZ6czBiTWRScllTSGEvQzM5a0NyY1A4a1ZwckU5ZitrUUFBQUg0d2ZBWUpLb1pJaHZjTkFRY0dvRzh3YlFJQkFEQm9CZ2txaGtpRzl3MEJCd0V3SGdZSllJWklBV1VEQkFFdU1CRUVEUGJmaDFpQk9jWEdGN000dFFJQkVJQTdVTk5KSlRZN01oY2M5blk4bUJNZEhUTFRjbC9HM1ZHMWxlbFFzYVNjazNIb2dJUGVkL25kM0tydFhvNUREcHZDK0d3Tk9MSlBvMmR0QVNNPSIsInZlcnNpb24iOiIyIiwidHlwZSI6IkRBVEFfS0VZIiwiZXhwaXJhdGlvbiI6MTUzNjE1NDUxNX0= https://756081124733.dkr.ecr.ap-northeast-1.amazonaws.com
      # - command
      # - command
    #finally:
      # - command
      # - command
  build:
    commands:
      - echo "docker build -t hgk/app ."
      - docker build -t hgk/app .

      # - command
      # - command
    #finally:
      # - command
      # - command
  post_build:
    - echo "docker push 756081124733.dkr.ecr.ap-northeast-1.amazonaws.com/hgk/app:latest"
    - docker tag hgk/app:latest 756081124733.dkr.ecr.ap-northeast-1.amazonaws.com/hgk/app:latest
    - docker push 756081124733.dkr.ecr.ap-northeast-1.amazonaws.com/hgk/app:latest
    #commands:
      # - command
      # - command
    #finally:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
    # - name
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - path
    # - path
